[MM-36011] reference mattermost github repo throughout code, not the authors
mattermost-community/mattermost-plugin-bitbucket pull request #29
Opened 2021-05-26 19:13 UTC by jfrerich

#### Summary
This PR substitutes all `github.com/kosgrz/mattermost-plugin-bitbucket` imports for `github.com/mattermost/mattermost-plugin-bitbucket`

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-36011

resolves https://github.com/mattermost/mattermost-plugin-bitbucket/issues/21

2021-06-01 07:34 UTC, larkox approved these changes

2021-06-04 17:49 UTC, hanzei requested changes
`.golangci.yml` need to be updated

2021-06-08 16:44 UTC, jfrerich commented
> `.golangci.yml` need to be updated

Nice catch, @hanzei.  Done.

2021-06-09 07:17 UTC, hanzei approved these changes
LGTM

2021-06-09 14:21 UTC, merged