Release v1.1.1
mattermost-community/mattermost-plugin-bitbucket pull request #49
Opened 2021-10-27 09:40 UTC by hanzei

#### Summary
Release for Marketplace

- [x] Requires https://github.com/mattermost/mattermost-plugin-bitbucket/pull/45 to be merged first

#### Ticket Link
Part of https://github.com/mattermost/mattermost-plugin-bitbucket/issues/46

2021-10-27 09:46 UTC, larkox approved these changes
LGTM, just one small comment.

2021-10-27 09:46 UTC, larkox commented on plugin.json
> +        "executable": ""
Probably nothing to worry about, but I found strange this change on the extructure.

2021-10-27 16:12 UTC, jfrerich requested changes
We should point these to the mattermost org now.

2021-10-27 16:12 UTC, jfrerich commented on plugin.json
> +        "footer": "* To report an issue, make a suggestion or a contribution, [check the repository](https://github.com/kosgrz/mattermost-plugin-bitbucket).",
```suggestion
        "footer": "* To report an issue, make a suggestion or a contribution, [check the repository](https://github.com/mattermost/mattermost-plugin-bitbucket).",
```

2021-10-27 16:12 UTC, jfrerich commented on plugin.json
> -        "footer": "* To report an issue, make a suggestion or a contribution, [check the repository](https://github.com/kosgrz/mattermost-plugin-bitbucket)."
```suggestion
        "footer": "* To report an issue, make a suggestion or a contribution, [check the repository](https://github.com/mattermost/mattermost-plugin-bitbucket)."
```

2021-10-28 07:51 UTC, hanzei commented
@jfrerich Good catch. Opened https://github.com/mattermost/mattermost-plugin-bitbucket/pull/50 for that.

2021-10-29 08:13 UTC, hanzei commented
@DHaussermann This is release is review for review

2021-10-29 14:37 UTC, jfrerich approved these changes

2021-11-02 19:25 UTC, DHaussermann commented
/update-branch

2021-12-01 22:15 UTC, hanzei commented
@DHaussermann This release is ready for review

2022-02-15 13:43 UTC, hanzei commented
/update-branch

2022-02-15 13:43 UTC, hanzei commented
@DHaussermann The release is ready for review

2022-03-02 17:36 UTC, DHaussermann commented
/update-branch

2022-03-21 15:25 UTC, DHaussermann commented
@aaronrothschild The code changes added since the initial release test have now been tested and passed.

After doing a quick smoke test there are 2 previously undocumented issues. In my judgment, these would not block the `v1.1.1` release. Please advise. If we're satisfied with solving theses in a future release - we can cut this and move on to the marketplace.  
  
https://github.com/mattermost/mattermost-plugin-bitbucket/issues/73 
https://github.com/mattermost/mattermost-plugin-bitbucket/issues/72

2022-03-21 17:07 UTC, aaronrothschild commented
Yes, let's fix thiose in a future release, let's cut it!  :). 🎉

2022-03-22 14:56 UTC, merged